module: ml_project.models.classification
class: ConvolutionalNeuralNetClassifier

#module: ml_project.model_selection
#class: GridSearchCV
#params:
#  n_jobs: -1
#  est_module: ml_project.pipeline
#  est_class: Pipeline
#  est_params:
#    - module: ml_project.models.feature_extraction
#      class: SampleFromRpeak
#    - module: sklearn.ensemble
#      class: RandomForestClassifier
#  param_grid: {}
#  cv:
#    module: sklearn.model_selection
#    class: KFold
#    params:
#      n_splits: 5
#      shuffle: True
#      random_state: 37