#Examples of config settings
#===========================
#Uncomment the example that you want to run
#Leave the first two lines of the example commented, though
#The second line of each example provides the command for the terminal

#Example 1
#smt run --config .config.yaml -X data/X_train.npy -a fit_transform
#module: ml_project.models.feature_selection
#class: RandomSelection
#params:
#  n_components: 1000
#  random_state: 37

#Example 2 (Warning: might exceed your memory)
#smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
#module: ml_project.models.regression
#class: KernelEstimator

#Example 3
#smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
#module: ml_project.pipeline
#class: Pipeline
#params:
#  class_list:
#    - module: ml_project.models.feature_selection
#      class: RandomSelection
#      params:
#        random_state: 37
#        n_components: 1000
#    - module: sklearn.linear_model
#      class: LinearRegression

#Example 4
#smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
#module: ml_project.model_selection
#class: GridSearchCV
#params:
#  est_module: ml_project.pipeline
#  est_class: Pipeline
#  est_params:
#    - module: ml_project.models.feature_selection
#      class: RandomSelection
#      params:
#        random_state: 37
#    - module: sklearn.linear_model
#      class: LinearRegression
#  param_grid:
#    RandomSelection__n_components:
#      - 100
#      - 1000
#      - 10000
#  cv:
#    module: sklearn.model_selection
#    class: KFold
#    params:
#      n_splits: 3
#      shuffle: True
#      random_state: 37

#---------------------------------------------------------------------------

#smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
# pipeline test =
#   zero column elim + std. scaler + variance thr + lin reg
#module: ml_project.pipeline
#class: Pipeline
#params:
#  class_list:
#    - module: ml_project.models.feature_selection
#      class: EliminateZeroColumns
#    - module: ml_project.models.preprocessing
#      class: StandardScaler
#    - module: ml_project.models.feature_selection
#      class: VarianceThreshold
#      params:
#        threshold: 0
#    - module: sklearn.linear_model
#      class: LinearRegression

#smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
#cv = elim zero columns + std. scaler + var thr + lin reg
#module: ml_project.model_selection
#class: GridSearchCV
#params:
#est_module: ml_project.pipeline
#est_class: Pipeline
#est_params:
#  - module: ml_project.models.feature_selection
#    class: EliminateZeroColumns
#  - module: ml_project.models.preprocessing
#    class: StandardScaler
#  - module: ml_project.models.feature_selection
#    class: VarianceThreshold
#  - module: sklearn.linear_model
##      class: LinearRegression    # for linear regression
#    class: Lasso                # for lasso
#param_grid:
#  VarianceThreshold__threshold:
#    - 0
#    - 0.1
#    - 0.2
#    - 0.5
#    - 0.9
#  Lasso__alpha:
#    - 2.0
#    - 1.0
#    - 0.7
#    - 0.5
#    - 0.1
#cv:
#  module: sklearn.model_selection
#  class: KFold
#  params:
#    n_splits: 10
#    shuffle: True
#    random_state: 37

#smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
# pipeline test =
#   intensity histogram + std.scaler + variance thr + lin reg
#module: ml_project.pipeline
#class: Pipeline
#params:
#  class_list:
#    - module: ml_project.models.feature_extraction
#      class: IntensityHistogram
#    - module: ml_project.models.preprocessing
#      class: StandardScaler
#    - module: ml_project.models.feature_selection
#      class: VarianceThreshold
#      params:
#        threshold: 0
#    - module: sklearn.linear_model
#      class: LinearRegression


#smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
#cv = elim zero columns + std. scaler + var thr + lin reg
#module: ml_project.model_selection
#class: GridSearchCV
#params:
#  est_module: ml_project.pipeline
#  est_class: Pipeline
#  est_params:
#    - module: ml_project.models.feature_extraction
#      class: IntensityHistogram
#    - module: ml_project.models.preprocessing
#      class: StandardScaler
#    - module: ml_project.models.feature_selection
#      class: VarianceThreshold
#    - module: sklearn.linear_model
#      class: LinearRegression
#  param_grid:
#    VarianceThreshold__threshold:
#      - 0
#      - 0.1
#      - 0.2
#      - 0.5
#      - 0.9
#    IntensityHistogram__bin_number:
#      - 45
#      - 100
#      - 450
#  cv:
#    module: sklearn.model_selection
#    class: KFold
#    params:
#      n_splits: 10
#      shuffle: True
#      random_state: 37


#smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
#cv = elim zero columns + std. scaler + var thr + lin reg
#module: ml_project.model_selection
#class: GridSearchCV
#params:
#  est_module: ml_project.pipeline
#  est_class: Pipeline
#  est_params:
#    - module: ml_project.models.feature_extraction
#      class: IntensityHistogram
#    - module: ml_project.models.preprocessing
#      class: StandardScaler
#    - module: ml_project.models.feature_selection
#      class: VarianceThreshold
#    - module: sklearn.kernel_ridge
#      class: KernelRidge
#  param_grid:
#    VarianceThreshold__threshold:
#      - 0
#      - 0.1
#      - 0.2
#    IntensityHistogram__bin_number:
#      - 45
#      - 100
#      - 450
#    KernelRidge__kernel:
#      - "linear"
#      - "rbf"
#      - "sigmoid"
#    KernelRidge__gamma:
#      - 0.01
#      - 0.1
#      - 1.0
#      - 10.0
#  cv:
#    module: sklearn.model_selection
#    class: KFold
#    params:
#      n_splits: 10
#      shuffle: True
#      random_state: 37


#smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
#cv = hisogram + std. scaler + var thr + ridge reg
#module: ml_project.model_selection
#class: GridSearchCV
#params:
#  n_jobs: -1
#  est_module: ml_project.pipeline
#  est_class: Pipeline
#  est_params:
#    - module: ml_project.models.feature_extraction
#      class: IntensityHistogram
#    - module: ml_project.models.preprocessing
#      class: StandardScaler
#    - module: ml_project.models.feature_selection
#      class: VarianceThreshold
#    - module: sklearn.linear_model
#      class: Ridge
#  param_grid:
#    VarianceThreshold__threshold:
#      - 0
#    IntensityHistogram__bin_number:
#      - 10
#      - 60
#      - 100
#      - 200
#    IntensityHistogram__x_cell_number:
#      - 16
#    IntensityHistogram__y_cell_number:
#      - 16
#    IntensityHistogram__z_cell_number:
#      - 16
#    Ridge__alpha:
#      - 0.01
#      - 0.1
#      - 1.0
#  cv:
#    module: sklearn.model_selection
#    class: KFold
#    params:
#      n_splits: 5
#      shuffle: True
#      random_state: 37


#smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
#cv = histogram + std. scaler + var thr + tree reg
#module: ml_project.model_selection
#class: GridSearchCV
#params:
#  est_module: ml_project.pipeline
#  est_class: Pipeline
#  est_params:
#    - module: ml_project.models.feature_extraction
#      class: IntensityHistogram
#    - module: ml_project.models.preprocessing
#      class: StandardScaler
#    - module: ml_project.models.feature_selection
#      class: VarianceThreshold
#    - module: sklearn.tree
#      class: ExtraTreeRegressor
#  param_grid:
#    IntensityHistogram__bin_number:
#      - 50
#      - 100
#      - 200
#      - 450
#    IntensityHistogram__x_cell_number:
#      - 8
##      - 16
#    IntensityHistogram__y_cell_number:
#      - 8
##      - 16
#    IntensityHistogram__z_cell_number:
#      - 8
##      - 16
#    VarianceThreshold__threshold:
#      - 0
#  cv:
#    module: sklearn.model_selection
#    class: KFold
#    params:
#      n_splits: 5
#      shuffle: True
#      random_state: 37


#smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
#cv = std. scaler + pca + ridge reg
#module: ml_project.model_selection
#class: GridSearchCV
#params:
#  est_module: ml_project.pipeline
#  est_class: Pipeline
#  est_params:
#    - module: ml_project.models.preprocessing
#      class: StandardScaler
#    - module: ml_project.models.preprocessing
#      class: PrincipleComponentAnalysis
#    - module: sklearn.linear_model
#      class: Ridge
#  param_grid:
#    PrincipleComponentAnalysis__n_components:
#      - 1000
#      - 2000
#      - 5000
#    Ridge__alpha:
#      - 0.01
#      - 0.1
#      - 1.0
#  cv:
#    module: sklearn.model_selection
#    class: KFold
#    params:
#      n_splits: 5
#      shuffle: True
#      random_state: 37



#smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
#cv = histogram + std. scaler + var thr + ridge reg
#module: ml_project.model_selection
#class: GridSearchCV
#params:
#  n_jobs: -1
#  est_module: ml_project.pipeline
#  est_class: Pipeline
#  est_params:
#    - module: ml_project.models.feature_extraction
#      class: IntensityHistogram
#    - module: ml_project.models.preprocessing
#      class: StandardScaler
#    - module: ml_project.models.preprocessing
#      class: PrincipleComponentAnalysis
#    - module: sklearn.linear_model
#      class: Ridge
#  param_grid:
#    IntensityHistogram__bin_number:
#      - 20
#      - 45
#      - 60
#      - 80
#    IntensityHistogram__x_cell_number:
#      - 16
#    IntensityHistogram__y_cell_number:
#      - 16
#    IntensityHistogram__z_cell_number:
#      - 16
#    PrincipleComponentAnalysis__n_components:
#      - 100
#      - 200
#      - 500
#      - 1000
#      - 2000
#    Ridge__alpha:
#      - 0.005
#      - 0.01
#      - 0.02
#      - 0.05
#      - 0.1
#  cv:
#    module: sklearn.model_selection
#    class: KFold
#    params:
#      n_splits: 5
#      shuffle: True
#      random_state: 37

#smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
#module: ml_project.model_selection
#class: GridSearchCV
#params:
#  n_jobs: -1
#  est_module: ml_project.pipeline
#  est_class: Pipeline
#  est_params:
#    - module: ml_project.models.feature_extraction
#      class: IntensityMean
#    - module: ml_project.models.preprocessing
#      class: StandardScaler
#    - module: ml_project.models.feature_selection
#      class: VarianceThreshold
#    - module: sklearn.linear_model
#      class: Ridge
#  param_grid:
#    IntensityMean__x_cell_number:
#      - 8
#      - 16
#    IntensityMean__y_cell_number:
#      - 8
#      - 16
#    IntensityMean__z_cell_number:
#      - 8
#      - 16
#    Ridge__alpha:
#      - 0.001
#      - 0.01
#      - 0.1
#      - 0.2
#  cv:
#    module: sklearn.model_selection
#    class: KFold
#    params:
#      n_splits: 3
#      shuffle: True
##      random_state: 37

###smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
#module: ml_project.model_selection
#class: GridSearchCV
#params:
#  n_jobs: -1
#  est_module: ml_project.pipeline
#  est_class: Pipeline
#  est_params:
#    - module: ml_project.models.feature_extraction
#      class: IntensityMeanAndMedian
#    - module: ml_project.models.preprocessing
#      class: StandardScaler
#    - module: ml_project.models.feature_selection
#      class: VarianceThreshold
#    - module: sklearn.linear_model
#      class: Ridge
#  param_grid:
#    IntensityMeanAndMedian__x_cell_number:
#      - 8
#      - 16
#      - 32
#    IntensityMeanAndMedian__y_cell_number:
#      - 8
#      - 16
#      - 32
#    IntensityMeanAndMedian__z_cell_number:
#      - 8
#      - 16
#      - 32
#    Ridge__alpha:
#      - 0.001
#      - 0.01
#      - 0.1
#      - 0.2
#      - 0.5
#  cv:
#    module: sklearn.model_selection
#    class: KFold
#    params:
#      n_splits: 3
#      shuffle: True
##      random_state: 37



#module: ml_project.pipeline
#class: Pipeline
#params:
#  class_list:
#    - module: ml_project.models.feature_extraction
#      class: IntensityHistogram
#    - module: ml_project.models.preprocessing
#      class: StandardScaler
#    - module: ml_project.models.feature_selection
#      class: VarianceThreshold
#    - module: ml_project.models.regression
#      class: KernelEstimator

#module: ml_project.models.feature_extraction
#class: MeanIntensityGradient


#module: ml_project.model_selection
#class: GridSearchCV
#params:
#  n_jobs: -1
#  est_module: ml_project.pipeline
#  est_class: Pipeline
#  est_params:
#    - module: ml_project.models.feature_extraction
#      class: IntensityMeanAndMedian
#    - module: ml_project.models.preprocessing
#      class: StandardScaler
#    - module: ml_project.models.feature_selection
#      class: VarianceThreshold
#    - module: sklearn.linear_model
#      class: Ridge
#  param_grid:
#    IntensityMeanAndMedian__x_cell_number:
#      - 8
#      - 16
#      - 32
#    IntensityMeanAndMedian__y_cell_number:
#      - 8
#      - 16
#      - 32
#    IntensityMeanAndMedian__z_cell_number:
#      - 8
#      - 16
#      - 32
#    Ridge__alpha:
#      - 0.001
#      - 0.01
#      - 0.1
#      - 0.2
#      - 0.5
#      - 0.7
#  cv:
#    module: sklearn.model_selection
#    class: KFold
#    params:
#      n_splits: 3
#      shuffle: True
##      random_state: 37


module: ml_project.model_selection
class: GridSearchCV
params:
  n_jobs: -1
  est_module: ml_project.pipeline
  est_class: Pipeline
  est_params:
    - module: ml_project.models.feature_extraction
      class: MeanIntensityGradient
    - module: ml_project.models.preprocessing
      class: StandardScaler
    - module: ml_project.models.feature_selection
      class: VarianceThreshold
    - module: sklearn.linear_model
      class: Ridge
  param_grid:
    IntensityMeanAndMedian__x_cell_number:
      - 8
      - 16
      - 32
    IntensityMeanAndMedian__y_cell_number:
      - 8
      - 16
      - 32
    IntensityMeanAndMedian__z_cell_number:
      - 8
      - 16
      - 32
    Ridge__alpha:
      - 0.001
      - 0.01
      - 0.1
      - 0.2
      - 0.5
      - 0.7
  cv:
    module: sklearn.model_selection
    class: KFold
    params:
      n_splits: 3
      shuffle: True
#      random_state: 37